export const SUPPORT_LANGUAGES = {
  en: 'English',
  'zh-Hans': '简体中文',
  'zh-Hant': '繁體中文',
  yue: '粤语',
  wyw: '古文',
  ja: '日本語',
  ko: '한국어',
  fr: 'Français',
  de: 'Deutsch',
  es: 'Español',
  it: 'Italiano',
  ru: 'Русский',
  pt: 'Português',
  nl: 'Nederlands',
  pl: 'Polski',
  ar: 'العربية',
  af: 'Afrikaans',
  am: 'አማርኛ',
  az: 'Azərbaycan',
  be: 'Беларуская',
  bg: 'Български',
  bn: 'বাংলা',
  bs: 'Bosanski',
  ca: 'Català',
  ceb: 'Cebuano',
  co: 'Corsu',
  cs: 'Čeština',
  cy: 'Cymraeg',
  da: 'Dansk',
  el: 'Ελληνικά',
  eo: 'Esperanto',
  et: 'Eesti',
  eu: 'Euskara',
  fa: 'فارسی',
  fi: 'Suomi',
  fj: 'Fijian',
  fy: 'Frysk',
  ga: 'Gaeilge',
  gd: 'Gàidhlig',
  gl: 'Galego',
  gu: 'ગુજરાતી',
  ha: 'Hausa',
  haw: 'Hawaiʻi',
  he: 'עברית',
  hi: 'हिन्दी',
  hmn: 'Hmong',
  hr: 'Hrvatski',
  ht: 'Kreyòl Ayisyen',
  hu: 'Magyar',
  hy: 'Հայերեն',
  id: 'Bahasa Indonesia',
  ig: 'Igbo',
  is: 'Íslenska',
  jw: 'Jawa',
  ka: 'ქართული',
  kk: 'Қазақ',
  mn: 'Монгол хэл',
  tr: 'Türkçe',
  ug: 'ئۇيغۇر تىلى',
  ur: 'اردو',
  vi: 'Tiếng Việt',
}

export type LanguageKey = keyof typeof SUPPORT_LANGUAGES

export const LANGUAGE_KEYS = Object.keys(SUPPORT_LANGUAGES) as LanguageKey[]

export function languageNameByKey(key: LanguageKey): string {
  return SUPPORT_LANGUAGES[key]
}
